### ISSUE TITLE
Problem: security / performance code errors and standardization

### ISSUE THREAD

**Issue by LaksCastro** [barbosamaatheus/english-talking-api#24]
General problem: security / performance code errors and standardization

Topic 1
The entire application is returning error messages that are unique in each file, that is, when the application is larger, there will be no simple way to maintain a standard error message.
Therefore, it would be interesting to add a file in which it exports a function that receives parameters that vary from error to error, and returns a standardized error response object, the same thing can be applied to successful responses.

Topic 2
In this file: https://github.com/Laks-Forks/english-talking-api/blob/develop/src/services/RegisterUserService.js#L12, on line 12, the user is being created in the database using req.body itself, which can cause conflicts if an API consumer sends a field that is not in the database model.

Topic 3
In the file https://github.com/Laks-Forks/english-talking-api/blob/develop/src/services/CreateDialogService.js, the then () and catch () function is being used to handle asynchronous requests, and it would be nice to switch to try and catch using async and await to maintain the default throughout the application.

Anything you disagree with, don't hesitate to answer and say the reason, I'm always willing to listen and learn.

Thank you :)

**Comment by barbosamaatheus** [comment]
Ok @LaksCastro, it`s sounds great.

You can do it

**Comment by LaksCastro** [comment]
Right, thanks for confirm

**Comment by barbosamaatheus** [comment]
Could you move the` jwt.verify` method to the **JWTGenerate** file? It would be nice to put everything about JWT in that file.

It would even be nice to change that name to **JWTManager** or something.

If possible, create **unit tests** for the two methods in this file.

Thank you very much in advance
