### ISSUE TITLE
Migrating to typescript

### ISSUE THREAD

**Issue by barbosamaatheus** [barbosamaatheus/english-talking-api#33]
**Is your feature request related to a problem? Please describe.**

No.

**Describe the solution you'd like**

This project must be built with typescript

**Describe alternatives you've considered**

Follow this tutorial:  https://www.typescriptlang.org/docs/handbook/migrating-from-javascript.html

**Comment by powilliam** [comment]
Hi there, i can deal with it!

**Comment by barbosamaatheus** [comment]
> Hi there, i can deal with it!

Ok @powilliam, thanks!!
