### ISSUE TITLE
Migrate the database to SQL postgres

### ISSUE THREAD

**Issue by barbosamaatheus** [barbosamaatheus/english-talking-api#35]
**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd like**

We are currently using NoSQL database. But I was studying a little and I believe that for our system the best would be SQL.  
I really like Postgres, would like it to be our database from now on.  
There should be no changes to the other functionality of the system. Make sure to ensure this. Only the database should be changed.  

**Describe alternatives you've considered**

I would like the solution to use if [Prisma](https://www.prisma.io/) as database tool kit.   
Prisma integrates better with typescript. You can wait until issue #33 is resolved or risk doing both at the same time ...

**Comment by Oseias447** [comment]
Olá poderia usar o TypeORM?  @barbosamaatheus 
https://typeorm.io/#/

**Comment by barbosamaatheus** [comment]
> Olá poderia usar o TypeORM? @barbosamaatheus
> https://typeorm.io/#/

Oii, pode sim! Pode fazer a sua escolha.
